# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xci
# IP: The module: 'embsys_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xci
# IP: The module: 'embsys_microblaze_0_axi_intc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_microblaze_0_axi_intc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
