# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache {C:/Users/Pine Xmas/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-18124-Pine-Ripper/incrSyn}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.cache/wt [current_project]
set_property parent.project_path D:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/Projects/Code/ECE544_Proj_GS/ece544_proj_gs_hardware/source/repositories/ece544ip-library-master
  d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/abhiraj_files/motor_measure_control_3.0
  d:/Projects/Code/ECE544_Proj_GS/ece544_proj_gs_hardware/source/repositories/vivado-library-v2019.1-1
} [current_project]
set_property ip_output_repo d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  D:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/new/PWDET.v
  D:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/new/PmodENC_decode.sv
}
read_verilog -library xil_defaultlib {
  D:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/new/debounce.v
  D:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/imports/hardware/nexysA7fpga.v
}
add_files D:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/embsys.bd
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_0/embsys_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/PmodENC_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/embsys_PmodENC_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/ip/PmodOLEDrgb_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_0/embsys_PmodOLEDrgb_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_0_0/embsys_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_uartlite_0_0/embsys_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_0/embsys_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_mdm_1_0/embsys_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_clk_wiz_1_0/embsys_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_rst_clk_wiz_1_100M_0/embsys_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_xbar_0/embsys_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_dlmb_v10_0/embsys_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_dlmb_v10_0/embsys_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_ilmb_v10_0/embsys_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_ilmb_v10_0/embsys_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_dlmb_bram_if_cntlr_0/embsys_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_ilmb_bram_if_cntlr_0/embsys_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_lmb_bram_0/embsys_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_1_0/embsys_axi_timer_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_1_0/embsys_axi_timer_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_timebase_wdt_0_0/embsys_axi_timebase_wdt_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_timebase_wdt_0_0/embsys_axi_timebase_wdt_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_2_0/embsys_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_2_0/embsys_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_2_0/embsys_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_uartlite_1_0/embsys_axi_uartlite_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_uartlite_1_0/embsys_axi_uartlite_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/ip/embsys_axi_uartlite_1_0/embsys_axi_uartlite_1_0.xdc]
set_property used_in_implementation false [get_files -all D:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/sources_1/bd/embsys/embsys_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/constrs_1/imports/constraints/nexysA7fpga.xdc
set_property used_in_implementation false [get_files D:/Projects/Code/ECE544_Proj_Final/code/ece544_proj_final/ece544_proj_final.srcs/constrs_1/imports/constraints/nexysA7fpga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top nexysA7fpga -part xc7a100tcsg324-1 -directive FewerCarryChains -retiming


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef nexysA7fpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file nexysA7fpga_utilization_synth.rpt -pb nexysA7fpga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
