# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xci
# IP: The module: 'embsys_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xci
# IP: The module: 'embsys_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_0_0/embsys_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
