# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/embsys_PmodENC_0_0.xci
# IP: The module: 'embsys_PmodENC_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/PmodENC_pmod_bridge_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_pmod_bridge_0_0 || ORIG_REF_NAME==PmodENC_pmod_bridge_0_0} -quiet] -quiet

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_axi_gpio_0_0 || ORIG_REF_NAME==PmodENC_axi_gpio_0_0} -quiet] -quiet

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_xlslice_0_0/PmodENC_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_0_0 || ORIG_REF_NAME==PmodENC_xlslice_0_0} -quiet] -quiet

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_xlslice_0_1/PmodENC_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_0_1 || ORIG_REF_NAME==PmodENC_xlslice_0_1} -quiet] -quiet

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_xlslice_0_2/PmodENC_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_0_2 || ORIG_REF_NAME==PmodENC_xlslice_0_2} -quiet] -quiet

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_xlslice_t_0_0/PmodENC_xlslice_t_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_t_0_0 || ORIG_REF_NAME==PmodENC_xlslice_t_0_0} -quiet] -quiet

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_xlconcat_0_0/PmodENC_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlconcat_0_0 || ORIG_REF_NAME==PmodENC_xlconcat_0_0} -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/PmodENC_pmod_bridge_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodENC_pmod_bridge_0_0 || ORIG_REF_NAME==PmodENC_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodENC_axi_gpio_0_0 || ORIG_REF_NAME==PmodENC_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0_ooc.xdc

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodENC_axi_gpio_0_0 || ORIG_REF_NAME==PmodENC_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/embsys_PmodENC_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_PmodENC_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_PmodENC_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/embsys_PmodENC_0_0.xci
# IP: The module: 'embsys_PmodENC_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/PmodENC_pmod_bridge_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_pmod_bridge_0_0 || ORIG_REF_NAME==PmodENC_pmod_bridge_0_0} -quiet] -quiet

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_axi_gpio_0_0 || ORIG_REF_NAME==PmodENC_axi_gpio_0_0} -quiet] -quiet

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_xlslice_0_0/PmodENC_xlslice_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_0_0 || ORIG_REF_NAME==PmodENC_xlslice_0_0} -quiet] -quiet

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_xlslice_0_1/PmodENC_xlslice_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_0_1 || ORIG_REF_NAME==PmodENC_xlslice_0_1} -quiet] -quiet

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_xlslice_0_2/PmodENC_xlslice_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_0_2 || ORIG_REF_NAME==PmodENC_xlslice_0_2} -quiet] -quiet

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_xlslice_t_0_0/PmodENC_xlslice_t_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlslice_t_0_0 || ORIG_REF_NAME==PmodENC_xlslice_t_0_0} -quiet] -quiet

# IP: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_xlconcat_0_0/PmodENC_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==PmodENC_xlconcat_0_0 || ORIG_REF_NAME==PmodENC_xlconcat_0_0} -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/PmodENC_pmod_bridge_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodENC_pmod_bridge_0_0 || ORIG_REF_NAME==PmodENC_pmod_bridge_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_pmod_bridge_0_0/src/pmod_concat_ooc.xdc

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodENC_axi_gpio_0_0 || ORIG_REF_NAME==PmodENC_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0_ooc.xdc

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==PmodENC_axi_gpio_0_0 || ORIG_REF_NAME==PmodENC_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/embsys_PmodENC_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_PmodENC_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Projects/Code/ECE544_Proj_02/ece-544-project-2-thongd_abhiraja/code/ece544_project_02/ece544_project_02.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_0/src/PmodENC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'embsys_PmodENC_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
